FROM node:20-slim

WORKDIR /app

COPY package.json package-lock.json* yarn.lock* ./

RUN npm ci || yarn install

COPY tsconfig.json ./

COPY src ./src
COPY scripts ./scripts
COPY data ./data

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]